spring:
  cloud:
    gateway:
      routes:
        - id: xiaoxupay-order
          uri: lb://xiaoxupay-order
          predicates:
            - Path=/order/**
        - id: xiaoxupay-site
          uri: lb://xiaoxupay-site
          predicates:
            - Path=/site/**
    nacos:
      config:
        server-addr: 
        file-extension:    #指定配置文件扩展名为yml
        username: 
        password: 
        namespace: pay-gateway
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - nacos:nacos-discovery.yml