server:
  port: 8013
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: xiaoxupay-gateway
  cloud:
    gateway:
      routes:
        - id: xiaoxupay-order
          uri: lb://xiaoxupay-order
          predicates:
            - Path=/order/**
        - id: xiaoxupay-site
          uri: lb://xiaoxupay-site
          predicates:
            - Path=/site/**
    nacos:
      config:
        server-addr: nacos_ip:nacos_port
        file-extension: yml   #指定配置文件扩展名为yml
        username: nacos_username
        password: nacos_password
        namespace: pay-gateway
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - nacos:nacos-discovery.yml


logging:
  config: classpath:log4j2-spring.xml
  level:
    com.alibaba.cloud.nacos: debug