server:
  port: 8899
spring:
  application:
    name: xiaoxupay-pay
  cloud:
    nacos:
      config:
        server-addr: nacos_ip:nacos_port
        file-extension: yml   #指定配置文件扩展名为yml
        username: nacos_username
        password: nacos_password
        namespace: pay-gateway
  config:
    import:
      - nacos:${spring.application.name}.yml
      - nacos:nacos-discovery.yml
      - nacos:db-common.yml    #数据库公共配置


logging:
  config: classpath:log4j2-spring.xml
  level:
    com.alibaba.cloud.nacos: debug