<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xujie</groupId>
        <artifactId>PayGateWay</artifactId>
        <version>1.0</version>
    </parent>
    <packaging>pom</packaging>
    <modules>
        <module>site-application</module>
        <module>site-infra</module>
        <module>site-controller</module>
        <module>site-domain</module>
        <module>site-common</module>
        <module>site-starter</module>
        <module>site-api</module>
    </modules>
    <artifactId>xiaoxupay-site</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.xujie</groupId>
            <artifactId>xiaoxupay-common</artifactId>
        </dependency>

    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>