server:
  port: 8011
spring:
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: xiaoxupay-order

logging:
  config: classpath:log4j2-spring.xml
  level:
    com.alibaba.cloud.nacos: debug