server:
  port: 8011
spring:
  application:
    name: xiaoxupay-order
  cloud:
    nacos:
      config:
        server-addr: 183.131.51.137:8848
        file-extension: yml   #指定配置文件扩展名为yml
        username: nacos
        password: xujie520.
        namespace: pay-gateway
  config:
    import:
      - nacos:${spring.application.name}.yml
      - nacos:db-common.yml    #数据库公共配置
      - nacos:nacos-discovery.yml
logging:
  config: classpath:log4j2-spring.xml
  level:
    com.alibaba.cloud.nacos: debug